import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./shared/nav/page";
import Contact from "./shared/contact/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className}>
        <Contact className="" />
        <Nav></Nav>
        {children}
      </body>
    </html>
  );
}
